name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deploy-command:
        required: true
        type: string
      branch-name:
        required: true
        type: string

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ID }}
          aws-region: us-east-1
          role-session-name: GithubActionsDeploymentJob

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy
        run: ${{ inputs.deploy-command }}
